# Note: Comments generated by ChatGPT; code is from Udemy

# Variables to indicate the status of a magician and their expertise
is_magician = True   # True if the person is a magician
is_expert = False    # True if the person is an expert magician

# Check the conditions for the magician's status
if is_expert and is_magician: 
    # If the person is both an expert and a magician
    print("You are a master magician")
    
elif is_magician and not is_expert:
    # If the person is a magician but not an expert
    print("At least you're getting there")
    
elif not is_magician:
    # If the person is not a magician
    print("You need magic powers")
