#note comments generated by chatgpt code is from udemy

# Define a function to print a greeting with a name and emoji
# def say_hello(name, emoji):
#     print(f'hellllooooo {name} {emoji}')
    
# # Positional arguments: calling the function with specific values for name and emoji
# say_hello('Andrei', "😎")
# say_hello('Dan', "😎")
# say_hello('Emily', "😎")

# # Keyword arguments: calling the function with the arguments specified by name
# say_hello(emoji='😋', name='Bibi')
    
# Default parameters: defining the function with default values for name and emoji
def say_hello(name='Darth Vader', emoji='😁'):
    print(f'hellllooooo {name} {emoji}')
    
# Positional arguments: using specific values for name and emoji
say_hello('Andrei', "😎")
say_hello('Dan', "😎")
say_hello('Emily', "😎")

# Keyword arguments: specifying values by name, overriding the default for emoji
say_hello(emoji='😋', name='Bibi')

# Positional argument: only providing a name, which uses the default emoji
say_hello('Timmy')

# No arguments: uses both default values for name and emoji
say_hello()    
